binance_creds:
  api_key: "${binance_key}"
  api_secret: "${binance_secret}"

finnhub:
  api_key: "finnhub_api_key" #os environment variable
  base_url: "https://finnhub.io/api/v1"


yahoo_finance:
  trending_url: "https://finance.yahoo.com/trending-tickers"

stock_categories:
  - AI
  - TECH
robinhood_tickers:
  - AAPL
  - AI
  - AMD
  - ARTY
  - BBAI
  - BOTZ
  - DIS
  - JMIA
  - MDB
  - MSFT
  - NEUE
  - NVDA
  - PLTR
  - PLUG
  - QCOM
  - RIOT
  - SOUN
  - TEAM
  - TSLA
  - UBER
  - VGT
  - WKHS
  - IONQ