binance_creds:
  api_key: "${binance_key}"
  api_secret: "${binance_secret}"

finnhub:
  api_key: "finnhub_api_key" #os environment variable
  base_url: "https://finnhub.io/api/v1"


yahoo_finance:
  trending_url: "https://finance.yahoo.com/trending-tickers"

stock_categories:
  - AI
  - TECH

robinhood:
  - AAPL
  - AI
  - AMD
  - ARTY
  - BBAI
  - BOTZ
  - DIS
  - JMIA
  - MDB
  - MSFT
  - NEUE
  - NVDA
  - PLTR
  - PLUG
  - QCOM
  - RIOT
  - TEAM
  - TSLA
  - UBER
  - VGT
  - WKHS
  - VST


quantum:
 - RGTI
 - IONQ
 - QBTS
 - QUBT
 - QSI
 - NVDA

ai:
 - AI
 - BBAI
 - TEM


monitor:
 - WDAY
 - SE
 - DDOG
 - RBLX
 - MCHP
 - AVGO
 - NFLX
 - ADBE
 - INTU
 - SHOP
 - APP
 - MRVL
 - SPOT
 - SMCI
