name: Run Trading Bot

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # Specify the Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run AutoBot
      env:
          finnhub_api_key: ${{ secrets.finnhub_api_key }}
      run: python prime.py
