name: Run Trading Bot

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from the Actions tab
  schedule:
    - cron: "0 13 * * *" # Runs at 8:00 AM EST (1:00 PM UTC)
    - cron: "0 17 * * *" # Runs at 12:00 PM EST (5:00 PM UTC)
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Robinhood Stocks
      env:
        finnhub_api_key: ${{ secrets.finnhub_api_key }}
      run: python prime.py --set args_group='Robinhood'

    - name: Run Manual List
      env:
        finnhub_api_key: ${{ secrets.finnhub_api_key }}
      run: python prime.py --set args_group='manual_list'

    - name: Run Yahoo Trending Stocks
      env:
        finnhub_api_key: ${{ secrets.finnhub_api_key }}
      run: python prime.py --set args_group='trending'

    - name: Run Finnhub AI and TECH Stocks
      env:
        finnhub_api_key: ${{ secrets.finnhub_api_key }}
      run: python prime.py --set args_group='categorical'
